### ISSUE TITLE
http://www.dobest.me/post/react-native-build-native-componenets/ not found

### ISSUE THREAD

**Issue by genie88** [ele828/react-native-guide#6]

**Comment by ele828** [comment]
Sorry, my website has turned down because of VPS invoice unpaid. You can read the article here :)
https://github.com/ele828/dobest.me/blob/master/React%20Native%E6%9E%84%E5%BB%BA%E6%9C%AC%E5%9C%B0%E8%A7%86%E5%9B%BE%E7%BB%84%E4%BB%B6.md

**Comment by genie88** [comment]
thanks a lot :+1:
