### ISSUE TITLE
this source is 404

### ISSUE THREAD

**Issue by daemonchen** [ele828/react-native-guide#9]
[构建一个简单的列表页和2页导航](http://www.xn--cnq920ntha.cn/archives/235#6838470-tsina-1-17436-6a377b1a66595f9ede646cf5c012734c) this page is 404.

**Comment by fatwin** [comment]
[Warning]! DO NOT click the link above. It looks like a phishing site.

**Comment by daemonchen** [comment]
@fatwin really? I copy it from the resource: [https://github.com/ele828/react-native-guide#react-native](https://github.com/ele828/react-native-guide#react-native)

- 构建一个简单的列表页和2页导航 http://www.xn--cnq920ntha.cn/archives/235#6838470-tsina-1-17436-6a377b1a66595f9ede646cf5c012734c

**Comment by daemonchen** [comment]
[fixed](https://github.com/ele828/react-native-guide/pull/12)
